### PR TITLE
Add "PyPI Quickstart" section to README.md

### PR DESCRIPTION
**Pull request by Akollek**
In addition to the PyPI docs, this PR also includes a few other markdown formatting fixes

### CODE REVIEW

**Comment by Akollek** [comment]
We've added a few steps outlining how we got validation working from within python, but please let us know if there are any omissions or easier ways of going about it!

I'm also aware that this readme gets pulled in as the help text for the command line executable, where the python docs are probably not so relevant. Let me know if you think we should move this docs to a subfolder and just link from the main readme.

**Comment by mdeforestbrown** [comment]
Would be great to update the pypi documentation too for future users who might miss this README if they download the package directly.

**Comment by Akollek** [comment]
> Would be great to update the pypi documentation too for future users who might miss this README if they download the package directly.

Good call, done! Also a point in favour of splitting out the python docs is that we could only show those in PyPI...

**Comment by nhaydel** [comment]
This is great! Thanks!

**Review by nhaydel — CHANGES_REQUESTED** [review]
Everything looks good, just need to fix the linter errors due to the changes in setup.py. You should just be able to run `black setup.py` to get those formatting changes fixed automatically.

**Comment by Akollek** [comment]
Fixed :)

**Review by nhaydel — APPROVED** [review]

**Pull request merged**
