### PR TITLE
add func for spilt datsets

### PR DESCRIPTION
**Pull request by ab3263266**
@SFJohnson24 Please check this solution to the issue we discussed last week

### CODE REVIEW

**Review by SFJohnson24 — DISMISSED** [review]
Code passes testing and high level review.  Changes pass Positive, Negative datasets for CG0017 as well as the split dataset negative from @RamilCDISC where the second dataset's name is noncompliant.

@ab3263266 could you add test coverage for the new build_split_datasets function?

**Review by SFJohnson24 — CHANGES_REQUESTED** [review]
@ab3263266 code functions well, see above request regarding adding some test coverage

**Comment by ab3263266** [comment]
@SFJohnson24 https://github.com/cdisc-org/cdisc-rules-engine/pull/700
Add unit tesing in a different PR

**Comment by gerrycampion** [comment]
@ab3263266 Is #672 fully included in #700? Can we close #672?

**Comment by ab3263266** [comment]
@gerrycampion טקד

**Pull request closed without merging**
