### PR TITLE
Parametrize progress bar

### PR DESCRIPTION
**Pull request by alexfurmenkov**
While working on a custom UI for the CORE engine we have identified the need to display the progress percentage as we had in the web version. 

Despite the fact that the CLI prints the progress bar to stdout by default, it is not very convenient to parse this progress bar on the desktop frontend and extract the percentage from it. So, in this PR I suggest parametrizing the progress bar in the following way - introduce a new parameter `-p, --progress` that can accept any of the following values:

- bar (default) - prints a progress bar like [████████████████████████████--------] 78%
- percents - prints only percents on new line like:
```
23
24
34
...
```
- disabled - disables the progress output (similarly to what `--disable-progressbar` flag does)

To preserve current behavior of the CLI, by default a progress bar is printed and instead of `--disable-progressbar` parameter we can pass `-p disabled`.

### CODE REVIEW

**Comment by nhaydel** [comment]
Doesn't the -vo flag already do this?

**Comment by alexfurmenkov** [comment]
> Doesn't the -vo flag already do this?

Can you please share the output of the command using this flag?

**Comment by alexfurmenkov** [comment]
> @alexfurmenkov your assessment is fair, I would like to add verbose_output as an option for the --progress flag.

Sure, will do. Can you please clarify what is expected from this option?

**Comment by nhaydel** [comment]
> > @alexfurmenkov your assessment is fair, I would like to add verbose_output as an option for the --progress flag.
> 
> Sure, will do. Can you please clarify what is expected from this option?

If provided it should log:
`[Level 51 2022-12-06 08:10:55,627 - console_logger.py:54] - CDISC.SDTMIG.CG0177 validation complete` as each rule is completed. It should log even if logging is disabled

**Comment by alexfurmenkov** [comment]
> > > @alexfurmenkov your assessment is fair, I would like to add verbose_output as an option for the --progress flag.
> > 
> > 
> > Sure, will do. Can you please clarify what is expected from this option?
> 
> If provided it should log: `[Level 51 2022-12-06 08:10:55,627 - console_logger.py:54] - CDISC.SDTMIG.CG0177 validation complete` as each rule is completed. It should log even if logging is disabled

So, you'd like to replace existing flag with this parameter, right?

**Comment by alexfurmenkov** [comment]
> > > > > @alexfurmenkov your assessment is fair, I would like to add verbose_output as an option for the --progress flag.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Sure, will do. Can you please clarify what is expected from this option?
> > 
> > 
> > > 
> > 
> > 
> > > If provided it should log: `[Level 51 2022-12-06 08:10:55,627 - console_logger.py:54] - CDISC.SDTMIG.CG0177 validation complete` as each rule is completed. It should log even if logging is disabled
> > 
> > 
> > So, you'd like to replace existing flag with this parameter, right?
> 
> Yes, like you did for percentage and progress bar, there should be an option for verbose that prints log statements for each rule completed

Added

**Review by nhaydel — APPROVED** [review]

**Pull request merged**
