### PR TITLE
rename parameters and add function

### PR DESCRIPTION
**Pull request by ab3263266**
fix bug 499 split datasets

 https://github.com/cdisc-org/cdisc-rules-engine/issues/499

### CODE REVIEW

**Review by RamilCDISC — CHANGES_REQUESTED** [review]
Could you please add a unit test which checks the bug mentioned in issue 499

**Comment by RamilCDISC** [comment]
Also when I ran a test using your branch,  I noticed some values (for debugging purpose i think so) were logged into the terminal.  Could you please remove it before we merge.

**Comment by ab3263266** [comment]
Hi @RamilCDISC,
I wanted to let you know that the values weren't from my code; I found the prints and deleted them. Additionally, I have added the unit testing and am now waiting for your approval.

Thank you.

**Review by RamilCDISC — CHANGES_REQUESTED** [review]
Thank you Ariel @ab3263266. Everything looks good. I did perform validation with negative and postive datasets. Just one small change before we can go for merging. Could you please move the dataset in the test file to a seprate json file. you can then just load the dataset from the file. This will make test more readable. You can keep the dataset file in resources folder under tests.

**Comment by ab3263266** [comment]
@RamilCDISC Done

**Review by SFJohnson24 — APPROVED** [review]
dataset passes high level review, positive and negative data validation works as expected

**Pull request merged**
