### PR TITLE
Add rule-blocking issue templates

### PR DESCRIPTION
**Pull request by gcampion-cdisc**
These templates are intended to assist the Rule Authors in submitting new bugs or feature requests when their rules are blocked.

### CODE REVIEW

**Comment by nhaydel** [comment]
I don't think we should include links to Jira tickets given that contributors may not have access to the JIRA project

**Comment by gcampion-cdisc** [comment]
> I don't think we should include links to Jira tickets given that contributors may not have access to the JIRA project

- I don't think it hurts to have these additional links. Even if the contributors don't have access to the jira project, it will provide traceability for the rule authors and those that do have access to the jira project.  However, the authors will need to ensure that all information required to resolve the ticket is included in the github ticket.
- I included the jira id in the github ticket title because this should allow the jira-github developer tools to automatically track the status of github commits and PRs that are created with the same jira id in the title.

**Review by alexfurmenkov — APPROVED** [review]

**Comment by gcampion-cdisc** [comment]
@alexfurmenkov @nhaydel 
I realized I based this off of main instead of dev. Should I merge or rebase dev into this branch and then merge this branch into dev?

**Comment by nhaydel** [comment]
> @alexfurmenkov @nhaydel I realized I based this off of main instead of dev. Should I merge or rebase dev into this branch and then merge this branch into dev?

I believe we are ok to merge into main. I also don't think this template will be applied unless it is in main so I am ok with that. I will try to merge development into main by the end of the week anyways

**Pull request merged**
